services:
  nextjs:
    build: .
    container_name: ironclad-nextjs
    restart: unless-stopped
    env_file:
      - .env.local
    environment:
      - NODE_ENV=production
    networks:
      - traefik

    labels:
      - "traefik.enable=true"

      # Router
      - "traefik.http.routers.ironclad.rule=Host(`traefik.mehdify.com`)"
      - "traefik.http.routers.ironclad.entrypoints=websecure"
      - "traefik.http.routers.ironclad.tls.certresolver=letsencrypt"
      - "traefik.http.routers.ironclad.service=ironclad"

      # Service
      - "traefik.http.services.ironclad.loadbalancer.server.port=3000"
      - "traefik.docker.network=traefik"

networks:
  traefik:
    external: true
